export const REGISTER_EMPLOYEE_REQUEST = 'REGISTER_EMPLOYEE_REQUEST';
export const REGISTER_EMPLOYEE_SUCCESS = 'REGISTER_EMPLOYEE_SUCCESS';
export const REGISTER_EMPLOYEE_FAILURE = 'REGISTER_EMPLOYEE_FAILURE';